### ISSUE TITLE
main.py For pipeline WITH scratch detection FAILS

### ISSUE THREAD

**Issue by gaseosaluz** [sanje2v/OldPhotoRestorationDLST#2]
`main.py` for pipelline with scratch detection fails. 

`python main.py --input_folder <Folder with images> --checkpoint ./weights/Image_Enhancement/stage1_with_scratch/tf_keras.weights ./weights/Image_Enhancement/stage2_with_scratch/tf_keras.weights ./weights/Face_Enhancement/stage3/tf_keras.weights --gpu_id 0`

running this command produces the following failure:

`Traceback (most recent call last):`
 ` File "main.py", line 163, in <module>`
  `  main(args)`
`  File "main.py", line 58, in main`
    `image_enhancer.load_weights(opts.checkpoint[next_checkpoint_index]).assert_consumed()`
  `File "/home/edm/miniconda3/envs/dalontf/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2216, in load_weights`
  `  status.assert_nontrivial_match()`
  `File "/home/edm/miniconda3/envs/dalontf/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py", line 826, in assert_nontrivial_match`
 `   "checkpointed value: %s") % (list(unused_python_objects),))`
`AssertionError: Nothing except the root object matched a checkpointed value. Typically this means that the checkpoint does not `
`match the Python program. The following objects have no matching checkpointed value: [<tf.Variable `
'image_enhancer/mapping_net/conv2d_23/bias:0' shape=(512,) dtype=float32, numpy=`
`array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,`
`       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,`
      
a long list of array printouts follow. 

Any ideas or suggestions? does this point to me having incorrectly converted the Pytorch weights? Or using the wrong models?

**Comment by sanje2v** [comment]
It looks like the code in the original repo has been updated and hence the checkpoint weights have also been modified. The new pretrained weights might have renamed layers and so you got the above error.

Please try the weights conversion step again with this weight: https://www.dropbox.com/s/km9a5syt0svymlb/OldPhotoCheckpoints.zip?dl=0 .

It is unlikely I'll be making modifications to this repo in the future to adapt the new changes and the old weights link (above) might be deleted whenever I need some space, so do make backups.

**Comment by gaseosaluz** [comment]
Great! Thanks for your prompt response.  I will download the weights tomorrow. If I get encouraging results on my side, I will try to figure out how to handle this on my own so that in the future I don’t have to trouble you again.  I will make sure that I make backups once I download the weights.

Again, many thanks!

**Comment by gaseosaluz** [comment]
Hello.  Again thank you for the help.  I downloaded the zip file  you provided, but I ran into the same issues.  

I did notice that the zip file you gave me did not have a new copy of a file called: `latest_net_G.pth` that goes in the `OldPhotoRestorationDLST/weights/Face_Enhancement/Setting_9_epoch_100` directory. Since I could not try the weight conversion without it, I used the file from the previous set of weights.  After I did that I was able to run the conversion scripts (I did get a bunch of warnings - but they were the same as before).  

However the test scripts failed - with the same errors as before. So I don't know if this is because I used the "old" ``latest_net_G.pt` from the directory above or I am missing something else.

If you can help me, I would be grateful, however I understand that you probably won't make any changes to your repo.  If this means that you can't help me or answer further questions, I will understand.  Just let me know if this is the case (that you can't help) and I will move on from this project.

**Comment by sanje2v** [comment]
Yeah, I seem to have missed some weights. Please download this instead: https://drive.google.com/file/d/1QUWVnVu-w3y8Ew6L8z1zMmEmSaWZepQp/view?usp=sharing .

**Comment by gaseosaluz** [comment]
Hi, I downloaded the new zip file with the updated `weights` directory.  The conversion scripts seemed to work, unfortunately the test scripts/commands still give me the same errors as I previously reported. I will try to start fresh again tomorrow by re-cloning your repo and downloading again the weights - just to make sure I did not accidentally mess things up. I welcome any suggestions.  As I said before, if you are unable to continue to look at this, just let me know.  In any case, I am grateful for your help and for taking the time.

**Comment by gaseosaluz** [comment]
I finally got around to test this again and unfortunately it still does not work.  So I assume that your work on the original Microsoft work are just way out of sync.  I understand that you will not be working on this anymore but I just wanted to leave this note here just in case somebody wants to try to go down the same road I went.

**Comment by AlexandruHeits** [comment]
Greetings,
I am having the same issues as @gaseosaluz .
Any updates, ideas or workarounds to sort this out?
Thanks in advance!

**Comment by sanje2v** [comment]
Hi @AlexandruHeits , because it's been a while that I have worked on this project and the TensorFlow version used then is now too old, unfortunately, I cannot aid you on this project and you will have to upgrade it yourself.
